language: en

pipeline:
  - name: SpacyNLP
    model: "en_core_web_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: LexicalSyntacticFeaturizer
    "features": [
      [ "low", "title", "upper", "pos", "pos2" ],
      [ "BOS", "EOS", "low", "upper", "title", "digit", "pos", "pos2" ],
      [ "low", "title", "upper", "pos", "pos2" ],
    ]
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    BILOU_flag: True
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
  - name: SpacyEntityExtractor
    dimensions: ["PERSON"]

policies:
- name: RulePolicy
  enable_fallback_prediction: True
  core_fallback_threshold: 0.3
  core_fallback_action_name: "utter_repeat_please"
