version: '3'

services:
  rasa:
    image: rasa/rasa:2.1.3-spacy-en
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  db:
    container_name: db
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=rasa_action_server
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=santa_bot
      - ALLOW_IP_RANGE='0.0.0.0/0'
    ports:
      - 5432:5432
