version: '3.7'

services:

  rasa_actions:
    container_name: rasa_actions
    build:
      context: .
    image: rasa_actions:0.0.1
    environment:
      - DB_HOST=xmas_db
    ports:
      - 5055:5055
    restart: on-failure

  xmas_db:
    container_name: xmas_db
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=rasa_action_server
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=santa_bot
      - ALLOW_IP_RANGE='0.0.0.0/0'
    ports:
      - 5432:5432
