name: Python checks

on: push

jobs:
  build:
    name: Python linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run pydocstyle
      run: |
        pydocstyle actions/ --count
        pydocstyle tests/ --count
    - name: Lint with Black
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        # stop the build if there are errors. The GitHub editor is 127 chars wide.
        flake8 . --count --show-source --statistics --max-complexity=10 --max-line-length=127
    - name: Lint with pylint
      run: |
        pylint actions/
        pylint tests/
    - name: Lint with isort
      run: |
        isort . --check --diff
    - name: Mypy check
      run: |
        mypy . --config-file mypy.ini
